---
- include: debian/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "Debian"

- include: redhat/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "RedHat"

- include: opensuse/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "Suse"

- include: config.yml
  tags: monit_config

- include: monitors.yml
  tags: monit_monitors

- include: service.yml
  tags: monit_service
